### ISSUE TITLE
🚩 Especificación Ontologías Hércules (80%)

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hercules-ontology#86]
El día 15 de mayo de 2020 se realiza la entrega del hito 1 para el proyecto hércules. Este issue representa el entregable _**Especificación Ontologías Hércules (80%)**_ del cual el tipo de entregable es: **_Especificación_**.

**Comment by thewillyhuman** [comment]
@spitxa podrías dar una estimación de lo que está hecho y lo que falta para completar este entregable?

**Comment by thewillyhuman** [comment]
**Tareas por hacer**
- [ ] Revisar documento y estilo (@spitxa)

**Comment by alejgh** [comment]
Esta es mi estimación de las cosas que necesitan añadirse a la ontología para completar las preguntas de competencia (es posible que no sea del todo exhaustiva, pero fueron las cosas que detecté):
- [x] Indicadores de producción científica (p.ej. número de citas, h-index...). Además a cada indicador habría que relacionarlo de alguna manera con la fecha (20 citas en 2018, 25 en 2019...). Con esto se cubren bastantes preguntas de competencia, como por ejemplo la #37, #35, #45, #32...
- [x] Una manera de enlazar universidades y centros.
- [x] Empresas y las relaciones entre ellas y los elementos actuales de la ontología. Ver #27 por ejemplo.
- [ ] Una manera de representar las líneas de investigación.
- [ ] Startups, spin-offs. Otros roles como por ejemplo socio, fundador... Ver #31.
- [x] Rematar el tema de las becas. Tenemos la clase Grant pero faltan maneras de enlazar con proyectos y otros elementos. -> isGrantedWith
- [ ] Niveles de madurez y ofertas tecnológicas. Ver #36 
- [x] Una manera de representar colaboraciones. Ver #49 y #50.
- [x] #48 es bastante específica y creo que faltarían bastantes cosas. El tema de las evaluaciones habría que añadirlo por ejemplo.
- [x] Menciones, como por ejemplo la mención cum laude. Ver #54 
- [ ] Añadir mucha información adicional sobre los proyectos. Por ejemplo:
    - [x] Estado (adjudicado, no adjudicado, en desarrollo, desarrollado.......)
    - [x] Tipo de participación de una persona en un proyecto. Investigador principal, colaborador externo...
    - [ ] Y otras... ver #19 
- [x] Añadir información adicional sobre investigadores. Por ejemplo el ORCID. No sé hasta que punto el uso de foaf:Person nos permite reutilizar propiedades y cuáles adicionales habría que añadir.
- [x] Añadir cantidades de dinero de las financiaciones. Actualmente se pueden añadir programas de financiación y enlazarlos con los proyectos, pero no sé si es posible añadir la cantidad de dinero específica de la financiación actualmente.
- [x] Datos sobre congresos, workshops... ver #28 
- [ ] Señalar quien es el titular/cotitular de las patentes. ver #41

Como he dicho la lista no es exhaustiva y seguramente mientras se añadan nuevas instancias y en el momento de crear las consultas SPARQL quizá se descubran nuevos elementos que hay que añadir. Aún así con esto se formaría una buena base.

**Comment by thewillyhuman** [comment]
@alejgh En cuanto se vayan completando las tareas las podéis is tachando de la lista haciendo click en la casilla correspondiente?
